### ISSUE TITLE
Incompatible with Python 3

### ISSUE THREAD

**Issue by valentjedi** [ivelum/codestyle#1]
I tried to check some Python3 project and found out that this image incompatible with Py3K features and syntax. For example, flake8 throws `NameError` at `FileNotFoundError` and throws `SyntaxError` at PEP 484 (type hints) syntax.

**Comment by stebunovd** [comment]
yeah - this tool was never tested vs. Python 3 projects. We're just preparing to migrate our projects to Python 3, so that wasn't a priority previously, but most likely will become a priority soon. BTW contributions are welcome )

**Comment by valentjedi** [comment]
I think we can close this issue, base Python 3 image can do codestyle checks for Python 2 projects as far as Py2 version uses Py3-compatible code. And we should consider it's a bug if such errors exists in first place.
